### ISSUE TITLE
OAuth login improvements

### ISSUE THREAD

**Issue by cmiacz** [saleor/saleor-cli#652]
```[tasklist]
### Tasks
- [x] Change localhost:5375 to 127.0.0.1:5375
- [x] Make sure Saleor CLI uses PKCE
- [x] Consider replacing current OAuth flow with [RFC 8628](https://datatracker.ietf.org/doc/html/rfc8628)
```

Keycloak deployent supports all mentioned features. 

RFC 8628 flow is:
```
      +----------+                                +----------------+
      |          |>---(A)-- Client Identifier --->|                |
      |          |                                |                |
      |          |<---(B)-- Device Code,      ---<|                |
      |          |          User Code,            |                |
      |  Device  |          & Verification URI    |                |
      |  Client  |                                |                |
      |          |  [polling]                     |                |
      |          |>---(E)-- Device Code       --->|                |
      |          |          & Client Identifier   |                |
      |          |                                |  Authorization |
      |          |<---(F)-- Access Token      ---<|     Server     |
      +----------+   (& Optional Refresh Token)   |                |
            v                                     |                |
            :                                     |                |
           (C) User Code & Verification URI       |                |
            :                                     |                |
            v                                     |                |
      +----------+                                |                |
      | End User |                                |                |
      |    at    |<---(D)-- End user reviews  --->|                |
      |  Browser |          authorization request |                |
      +----------+                                +----------------+
```

**Comment by zaiste** [comment]
All those points are implemented and available on staging corresponding to the Keycloack configuration in the cloud. Let us know before the production switch @cmiacz
